### ISSUE TITLE
Issue with ONLY AMPLICONS running mode

### ISSUE THREAD

**Issue by amarcog** [lucapinello/CRISPResso#19] opened 2017-05-16 10:05 UTC
Hello,

I am trying to run CRISPRessoPooled in ONLY AMPLICONS mode. I have a problem into the generation of reads file, I think related with the following reported information into the _RUNNING_LOG file: 

No samples; assembling all-inclusive block
  Sorting block of length 1074 for bucket 1
  (Using difference cover)
Error: reads file does not look like a FASTQ file
Error: Encountered exception: 'Unidentified exception'

I am already starting into bioinformatic analysis so I am not able to understand what it is happening. Furthermore, I couldn't find an example of this running mode to try solving the problem by my shelf. I attached the complete _RUNNING_LOG file and the input files.

[AMPLICONS.txt](https://github.com/lucapinello/CRISPResso/files/1003931/AMPLICONS.txt)
[AV4T6XXXX1.fastq.gz](https://github.com/lucapinello/CRISPResso/files/1003932/AV4T6XXXX1.fastq.gz)
[AV4T6XXXX2.fastq.gz](https://github.com/lucapinello/CRISPResso/files/1003933/AV4T6XXXX2.fastq.gz)
[CRISPRessoPooled_RUNNING_LOG.txt](https://github.com/lucapinello/CRISPResso/files/1004268/CRISPRessoPooled_RUNNING_LOG.txt)

The program must be work because in CRISPResso mode I am able to reproduce the results obtained from the online version. But our design of sequencing experiments requires the Pooled version to make the analysis more easy and automatic.

Thank you so much for your attention,

Andrés Marco Giménez
Phd Student
Institute for Bioengineering of Catalonia (IBEC)

**Comment by lucapinello** [comment] 2017-05-16 13:39
Hi Marco,
This may be related to bowtie2 and your fastq files, could you please try to align your fastq files without using crispresso and just with bowtie2 to your reference genome?

Probably some lines in the fastq files are malformed.

In CRISPResso you don't get this error since we are using internally another aligner (needle).
In CRISPRessoPooled bowtie2 is only used to demultiplex reads and assign them to each of the amplicon specified in the AMPLICONS.txt file.

Please let me know how it goes.

**Comment by amarcog** [comment] 2017-05-17 09:54
Hi Luca,

Thanks for your answer. I tried running bowtie alone and it blocks while it is indexing the reference genome. I attached terminal information:

[bowtie test.txt](https://github.com/lucapinello/CRISPResso/files/1007242/bowtie.test.txt)

I have followed:

http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#getting-started-with-bowtie-2-lambda-phage-example

And only .1.bt2, .2.bt2, .3.bt2, .4.bt2 have been generated. NOT .rev.1.bt2 and .rev.2.bt2.

In any case, is it needed to use a genome of reference? Could I avoid this? I don't understand why it is needed in ONLY AMPLICONS mode because (if i understood well) reference sequences must be those provided in the AMPLICONS.txt.

Thank you so much for your attention,

Andres

**Comment by lucapinello** [comment] 2017-05-17 14:56
Andres so it seems the problem is bowtie2 and not CRISPResso. Unfortunately you need to have a working version of Bowtie2  in order to use CRISPRessoPooled.

Internally I use Bowtie2 to build a custom index for the amplicon sequences you provide in the amplicon description file. Then the reads are aligned to those amplicons as a quick way to demultiplex them. Then each resulting file is used for the CRISPResso analysis.

Hope this is help.

Best,

Luca

**Comment by lucapinello** [comment] 2017-05-20 14:45
Andres, I will close this for now. If you find any problem with CRISPResso after you fix your problem with Bowtie2 please let me know.

**Closed as completed by lucapinello** 2017-05-20 14:45 UTC

**Comment by amarcog** [comment] 2017-05-20 14:55
Hi Luca,

Thank you again for your help. I will try to solve the problem with Bowtie.
In any case I could use the CRISPResso simple commands to generate a script
and automatize the analysis.

Your tool is very useful for our work,

Best regards

Andrés

El 20/5/2017 16:45, "Luca Pinello" <notifications@github.com> escribió:

Closed #19 <https://github.com/lucapinello/CRISPResso/issues/19>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lucapinello/CRISPResso/issues/19#event-1090557355>, or mute
the thread

**Comment by lucapinello** [comment] 2017-05-20 15:11
Thanks Andres!
